license = "LGPL-3.0-or-later"

modLoader = "javafml"
loaderVersion = "${loader}"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "Dipilodopilasaurus"
description = "${description}"
logoFile = "assets/papi/icon.png"
displayURL = "https://github.com/dipilo/Put-A-Plug-In-it"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "${loader}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
